#!/usr/bin/env python3

from bs4 import BeautifulSoup
from feedgen.feed import FeedGenerator
import datetime
import os
import pytz
import re

html_file_path = '_website/index.html'
with open(html_file_path, 'r', encoding='utf-8') as file:
    html_content = file.read()

soup = BeautifulSoup(html_content, 'html.parser')

fg = FeedGenerator()

fg.title('Augusto Coronel')
fg.link(href='https://aocoronel.github.io')
fg.description('Hello!')
fg.language('en-us')

for item in soup.select('h2[data-number]'):
    fe = fg.add_entry()

    title_tag = item.find('a')
    title = title_tag.text
    link = 'https://aocoronel.github.io/' + title_tag['href']

    date_tag = item.find_next('p')

    date_match = re.search(r'Posted on ([A-Za-z]+\s+\d{1,2},\s+\d{4})', date_tag.get_text())
    if date_match:
        date_str = date_match.group(1)
        naive_datetime = datetime.datetime.strptime(date_str, '%b %d, %Y')
        timezone = pytz.timezone('UTC')
        pub_date = timezone.localize(naive_datetime)
    else:
        print(f"Date not found in: {date_tag.get_text()}")
        continue

    description_tag = item.find_next('blockquote')
    description = description_tag.get_text().strip()

    fe.title(title)
    fe.link(href=link)
    fe.description(description)
    fe.pubDate(pub_date)

rss_feed = fg.rss_str(pretty=True)

if isinstance(rss_feed, bytes):
    rss_feed = rss_feed.decode('utf-8')

output_file_path = '_website/feed.xml'
os.makedirs(os.path.dirname(output_file_path), exist_ok=True)

try:
    with open(output_file_path, 'w', encoding='utf-8') as file:
        file.write(rss_feed)
    print("RSS feed generated successfully!")
except Exception as e:
    print(f"An error occurred while writing the file: {e}")
