#!/usr/bin/env bash

WEBSITE_DIR=_website
SOURCE_DIR=_posts
MASTER=0

main() {
  # shellcheck disable=2128
  case "$MASTER" in
  0)
    [ -z "$subdirs" ] && mapfile -t subdirs < <(find "$SOURCE_DIR" -maxdepth 1 -type d)

    for SUB_DIR in "${subdirs[@]}"; do
      case "$SUB_DIR" in
      _posts/media)
        continue
        ;;
      _posts)
        continue
        ;;
      _posts/_posts)
        continue
        ;;
      esac

      source_files=$(find "$SUB_DIR" -maxdepth 1 -type f -name "????-??-??-*" | sort -r)

      [ -f "$SUB_DIR-index.md" ] && rm "$SUB_DIR-index.md"

      for file in $source_files; do
        makeIndex "$file"
        cleanup
      done

      SUB_DIR=$(basename "$SUB_DIR")
      bash build-pages "$SOURCE_DIR/$SUB_DIR/index.md"
      rm "$SOURCE_DIR/$SUB_DIR/index.md"
    done

    echo "Indexes built."
    ;;
  1)
    # Generate master Index
    source_files=$(find "$SOURCE_DIR" -type f -name "????-??-??-*.md" | sort -t/ -k3r)

    for file in $source_files; do
      makeIndex "$file"
      cleanup
    done

    bash build-pages index.md
    rm index.md
    echo "Master Index built"
    ;;
  esac
}

cleanup() {
  unset IMG_FILEPATH
}

createHeader() {
  local CATEGORY=$1
  # shellcheck disable=SC2129
  echo "---" >>"$index_path"
  echo "title: Augusto Coronel" >>"$index_path"
  echo "category: $CATEGORY" >>"$index_path"
  case "$SUB_DIR" in
  _posts/tech)
    echo "description: Read about Linux, Programming and Commandline" >>"$index_path"
    ;;
  _posts/vet)
    echo "description: Under construction" >>"$index_path"
    ;;
  *)
    echo "description: Welcome to my blog! Here I talk about Tech, Veterinary Medicine and more!" >>"$index_path"
    ;;
  esac
  echo "---" >>"$index_path"
}

makeIndex() {
  local file=$1

  FILEPATH=$(basename "$file" .md)

  if [ "$MASTER" -eq 1 ]; then
    [ -f "$WEBSITE_DIR/media/$FILEPATH.avif" ] && IMG_FILEPATH="media/$FILEPATH.avif"
  else
    [ -f "$WEBSITE_DIR/media/$FILEPATH.avif" ] && IMG_FILEPATH="../media/$FILEPATH.avif"
  fi

  if [ "$MASTER" -eq 1 ]; then
    FILEPATH="$(basename "$(dirname "$file")")/$FILEPATH.html"
  else
    FILEPATH="$FILEPATH.html"
  fi

  FILE_TITLE=$(head -n 20 "$file" | grep "title:" | awk -F "title: " '{print $2}')
  FILE_DESCRIPTION=$(head -n 20 "$file" | grep "description:" | awk -F "description: " '{print $2}')
  POSTED_DATE=$(head -n 20 "$file" | grep "date:" | awk -F "date: " '{print $2}')
  CATEGORY=$(head -n 20 "$file" | grep "category:" | awk -F "category: " '{print $2}')

  generateIndex
}

generateIndex() {
  local index_path

  index_path="index.md"
  [ -n "$SUB_DIR" ] && index_path="$SUB_DIR/index.md"

  [ ! -f "$index_path" ] && {
    case "$MASTER" in
    1)
      createHeader "Master"
      ;;
    0)
      createHeader "$CATEGORY"
      ;;
    esac
  }

  # shellcheck disable=SC2129
  echo "## [$FILE_TITLE]($FILEPATH)" >>"$index_path"
  echo "" >>"$index_path"
  echo "Posted on **$POSTED_DATE** • **$CATEGORY**" >>"$index_path"
  echo "" >>"$index_path"
  echo "> $FILE_DESCRIPTION" >>"$index_path"
  echo "" >>"$index_path"
  [ -n "$IMG_FILEPATH" ] && echo "![]($IMG_FILEPATH)" >>"$index_path"
  echo "" >>"$index_path"
}

while getopts ":m" opt; do
  case "$opt" in
  m)
    MASTER=1
    ;;
  ?)
    echo "ERROR: Invalid option '-$OPTARG'" >&2
    exit 1
    ;;
  esac
done

shift $((OPTIND - 1))

main
