#!/usr/bin/env bash

SOURCE_DIR=_posts
index_path="index.md"

main() {
  # shellcheck disable=2128
  source_files=$(find -L "$SOURCE_DIR" -type f -name "????-??-??-*.md" | sort -t/ -k3r)

  createHeader

  echo "---" >>"$index_path"
  echo "" >>"$index_path"
  echo "# Posts" >>"$index_path"

  for file in $source_files; do
    makeIndex "$file"
  done

  [ -f "./_pages/custom-index.md" ] && cat ./_pages/custom-index.md >>"$index_path"

  bash build-pages index.md
  rm index.md
  echo "Index built"
}

createHeader() {
  # shellcheck disable=SC2129
  echo "---" >>"$index_path"
  echo "title: Augusto Coronel" >>"$index_path"
  echo "description: I’m a tech enthusiast and programming self-taught hobbist. I build CLIs for Linux." >>"$index_path"
  echo "---" >>"$index_path"
}

makeIndex() {
  local file=$1

  FILEPATH=$(basename "$file" .md)

  FILEPATH="$(basename "$(dirname "$file")")/$FILEPATH.html"

  FILE_TITLE=$(head -n 20 "$file" | grep "title:" | awk -F "title: " '{print $2}')
  POSTED_DATE=$(head -n 20 "$file" | grep "date:" | awk -F "date: " '{print $2}')

  generateIndex
}

generateIndex() {
  # shellcheck disable=SC2129
  echo "$POSTED_DATE • [$FILE_TITLE]($FILEPATH)" >>"$index_path"
  echo "" >>"$index_path"
}

[ -f "$index_path" ] && rm "$index_path"

main
